server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件
  type-aliases-package: com.atguigu.springcloud.entity #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper映射文件

spring:
  application:
    name: microservicecloud-dept   #这个名字很重要，很重要很重要。他是对外暴露的微服务名称，当使用eureka时，进入eureka页面后，就会看到这个名字。
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01   #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
#eureka客户端配置，告诉服务8001入住到注册中心eureka中      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #单机版用法  defaultZone: http://localhost:7001/eureka  #对应eureka服务端的defaultZone
  instance:
    instance-id: microservicecloud-dept8001 # 用于设置在eureka管理页面中，status列中显示的服务名称名字。此处不设置，将显示默认服务名字
    prefer-ip-address: true                 # 访问路径可以显示IP地址（鼠标指向status列中的名字是，浏览器左下角可以显示出服务的ip地址）
    
#eureka管理页面，status列中服务名，点开后，连接地址info url对应的页面显示配置。此处配置的内容，都会在info页面中显示。这样就不会在显示404了    
info: 
  app.name: atguigu-microservicecloud
  company.name: www.aiguigu.com
  build.artifactId: microservicecloud-provider-dept-8001  #父工程的pom文件中的plugin插件配置的$
  build.version: 0.0.1-SNAPSHOT        #父工程的pom文件中的plugin插件配置的$